global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'youtube-clone-app'
    static_configs:
      - targets: ['${APP_SERVER_HOST}:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['${APP_SERVER_HOST}:9100']
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s